matrix:
  include:
    - language: node  
      node: 
        - 5.8
      before_install:
        - cd client
      install:
        - npm install
      script: 
        - npm run dev
    - language: perl  
      perl: 
        - 5.26
      addons:
        apt:
          packages:
            - libmysqlclient-dev
      before_install:
        - cd server
      install:
        - cpanm --installdeps --notest .
      script: 
        - prove -v -I lib t/
    