matrix:
  include:
    - language: node_js  
      node_js: 
        - stable
      before_install:
        - cd client
        - cp config/dev.json.example config/dev.json
      install:
        - npm install
      script: 
        - npm run dev
    - language: perl  
      perl: 
        - 5.26
      addons:
        apt:
          packages:
            - libmysqlclient-dev
      before_install:
        - cd server
      install:
        - cpanm --installdeps --notest .
      script: 
        - prove -v -I lib t/
    