language: perl

perl: 
  - 5.26

addons:
  apt:
    packages:
      - libdbd-mysql-perl

before_install:
  - cd server

install:
  - 
  - cpanm --installdeps --notest .
  
script: 
  - prove -v -I lib t/