requires 'CHI';
requires 'LWP::UserAgent';
requires 'Module::Loader';
requires 'Mojo::DOM';
requires 'Moo';
requires 'Method::Signatures';
requires 'Text::Trim';
requires 'WebService::Spotify';
requires 'XML::Feed';
